# Numpy:
<a id='h_cell'></a>


|#NO|Topic|Status|
|--:|:---          |--:|
|01| [Terminology](#ter_cell)||
|02| [Getting information](#gi_cell)|
|03| [***Random***](#random_cell)|
|04| [***Create Numpy***](#carray_cell)|
|05| [Numpy Data Type](#dtype_cell)|
|06| [***Math and Logic Numpy***](#math_cell)|
|07| [***Manipulating Shape or Braodcasting***](#mts_cell)|
|08| [***Array Accessing***](#aa_cell)|
|09| [***Frequently used method***](#im_cell)|

In [126]:
import numpy as np
import math

## [1. Terminology](#h_cell)
<a id='ter_cell'></a>
A brief note about Numpy and their number of dimensions, and terminology:
1. O-dimensional tensor called a *scaler*.
2. 1-dimensional tensor called a *vector*.
3. Likewise, a 2-dimensional tensor is often referred to as a *matrix.*
4. Anything with more than two dimensions is generally just called a multi dimentional numpy array or tensor.

1. Scaler:

In [127]:
scaler= np.random.rand(1)
scaler.ndim, scaler.shape, scaler.item(), scaler, type(scaler), scaler

(1,
 (1,),
 0.21778467156990178,
 array([0.21778467]),
 numpy.ndarray,
 array([0.21778467]))

2. **Vector:** Algebraically, a vector is a collection of coordinates of a point in space. Thus, a vector with two values represents a point in a 2-dimensional space. In Computer Science, a vector is an arrangement of numbers along a single dimension. It is also commonly known as an array or a list or a tuple.

In [ ]:
vector= np.array([7,8])
print(type(vector), vector, vector.ndim, vector.shape)

<class 'numpy.ndarray'> [7 8] 1 (2,)


<class 'numpy.ndarray'> [7 8] 1 (2,)


3. **Matrix: 2 dimentional**

In [ ]:
## Matrix
MATRIX=np.array([[7, 8], 
                    [9, 10]])
print(type(MATRIX))
MATRIX,MATRIX.shape, MATRIX.ndim,MATRIX.dtype

<class 'numpy.ndarray'>


(array([[ 7,  8],
        [ 9, 10]]),
 (2, 2),
 2,
 dtype('int64'))

4. **Tensor or Multi-dimentional:**

In [ ]:
# Tensor
TENSOR = np.array([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR, TENSOR.shape, TENSOR.ndim, type(TENSOR)

(array([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]]),
 (1, 3, 3),
 3,
 numpy.ndarray)

In [ ]:
tensor=np.array([[[1, 2, 3,4], [4, 5, 6,4]], [[7, 8, 9,4], [10, 11, 12,4]], [[13, 14, 15,4], [16, 17, 18,4]]])
tensor.shape, tensor.ndim, 

((3, 2, 4), 3)

## [2. Getting Information:](#h_cell)
<a id='gi_cell'></a>
1. type(x): type(tensor) will return the type of the numpy object.
2. x.dtype: tensor.dtype will give you the data type.
3. x.shape: tensor.shape will give you the shape of the numpy object.
4. x.size: tensor.size will give you the total number of elements.
5. x.ndim: The ndim attribute of a PyTorch tensor returns the number of dimensions (rank) of the object.

In [ ]:
# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get type of the array
print(type(array))

# Get data type of the array
print(array.dtype)

# Get shape of the array
print(array.shape)

# Get total number of elements in the array
print(array.size)

# Get number of dimensions of the array
print(array.ndim)

# Get name of the data type
print(array.dtype.name)

<class 'numpy.ndarray'>
int64
(2, 3)
6
2
int64


In [ ]:
vector= np.array([7,8])
print(type(vector), vector, vector.ndim, vector.shape)
matrix_1=np.array([[1,2],[2,3], [4,5]])
print("Matrix Info: ",type(matrix_1), matrix_1, matrix_1.ndim, matrix_1.shape)
matrix_2= np.random.rand(3,2,5)
print("Matrix-2 Info: ",type(matrix_2),"\n", matrix_2, matrix_2.ndim, matrix_2.shape)

<class 'numpy.ndarray'> [7 8] 1 (2,)
Matrix Info:  <class 'numpy.ndarray'> [[1 2]
 [2 3]
 [4 5]] 2 (3, 2)
Matrix-2 Info:  <class 'numpy.ndarray'> 
 [[[0.72425703 0.44047231 0.55126556 0.22610508 0.4520969 ]
  [0.04737726 0.4067457  0.0286462  0.45653998 0.89241741]]

 [[0.37371932 0.954468   0.92234067 0.95726848 0.63558874]
  [0.81701614 0.45120818 0.46644239 0.14136992 0.09918282]]

 [[0.83980198 0.01803526 0.54953043 0.39435354 0.1090978 ]
  [0.1445535  0.09817036 0.02448567 0.72130882 0.23363193]]] 3 (3, 2, 5)


**Note:** 

1. $shape=(2,)$ means that a 1-D arrray and index 0 has 2 elements.
1. $shape=(3,2,5)$ means that a 2-D arrray and index[0] has 3 elements and index[1] has 2 elements and index[2] has 5 elements.

## [3. numpy.random():](#h_cell)
<a id='random_cell'></a>
This module contains the functions which are used for generating random numbers.

Methods:

1. `np.random.rand(d0, d1, ..., dn)`: This function of random module is used to generate random numbers or values in a given shape.
2. `np.random.randn(d0, d1, ..., dn)`: This function of random module return a sample from the ***standard normal*** distribution.
3. `np.random.randint(low, high=None, size=None, dtype=int)`: generate random integers from inclusive(low) to exclusive(high).
4. `np.random.random_integers(low, high=None, size=None)`: generate random integers number of type np.int between low and high.
5. `numpy.random.uniform(low=0.0, high=1.0, size=None)`:  generate random floating-point numbers within a specified range.
6. `numpy.random.choice(a, size=None, replace=True, p=None)`: Generates a random sample from a given 1-D array.
7. `numpy.random.normal(loc=0.0, scale=1.0, size=None)`: Draw random samples from a normal (Gaussian) distribution.
8. `numpy.random.shuffle(x):` reorder the elements.

### Creating array:
1. np.random.rand(d0, d1, ...dn)
2. np.random

In [ ]:
## np.random.rand
x= np.random.randint(2,50,(3,3))
x_ran_choice= np.random.choice(2,100,50)
print(x.shape,"\n",x)
print(f"x_ran_choice:{x_ran_choice}")

(3, 3) 
 [[48  8 45]
 [20 14  3]
 [ 3 13 34]]
x_ran_choice:[0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 0 1
 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1 1 1 1 0 1 0 0 1]


In [ ]:
np.random.seed(100)
a= np.random.randn(2,3,4)
a, a.shape, a.ndim, a[1], a[0]

(array([[[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
         [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
         [-0.18949583,  0.25500144, -0.45802699,  0.43516349]],
 
        [[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
         [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
         [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]]]),
 (2, 3, 4),
 3,
 array([[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
        [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
        [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]]),
 array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
        [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
        [-0.18949583,  0.25500144, -0.45802699,  0.43516349]]))

### Multiplication Rule:

In [ ]:
import numpy as np

In [ ]:
a= np.random.rand(2,3,3)
b= np.random.rand(1,3)
print("A: ", a, a.shape, a.ndim)
print("B: ", b, b.shape, b.ndim)
print("a*b=",a*b)
print("np.matmul(a,b)=",np.matmul(a,b.T))
print("b-Shape:",b.shape,"after transpose:", b.T.shape)

A:  [[[0.03647606 0.89041156 0.98092086]
  [0.05994199 0.89054594 0.5769015 ]
  [0.74247969 0.63018394 0.58184219]]

 [[0.02043913 0.21002658 0.54468488]
  [0.76911517 0.25069523 0.28589569]
  [0.85239509 0.97500649 0.88485329]]] (2, 3, 3) 3
B:  [[0.35950784 0.59885895 0.35479561]] (1, 3) 2
a*b= [[[0.01311343 0.53323093 0.34802642]
  [0.02154962 0.53331141 0.20468212]
  [0.26692727 0.37739129 0.20643506]]

 [[0.00734803 0.12577629 0.1932518 ]
  [0.27650294 0.15013108 0.10143454]
  [0.30644272 0.58389136 0.31394207]]]
np.matmul(a,b)= [[[0.89437077]
  [0.75954314]
  [0.85075362]]

 [[0.32637613]
  [0.52806855]
  [1.20427615]]]
b-Shape: (1, 3) after transpose: (3, 1)


## [4. Create Numpy Array](#h_cell)
<a id='carray_cell'></a>

1. `np.array()`: create a numpy array.
2. `np.random.rand()`: create a random numpy array with given shape.
3. `np.ones((2,3))`: create a tensor with one.
4. `np.zeors()`: create a tensor with $0$
5. `np.arange(start, end, step)`:
6. `np.empty()`: The `np.empty()` call allocates memory for the tensor, but does not initialize it with any values - so what you're seeing is whatever was in memory at the time of allocation.
6. ``np.*_like(x)`: Often, when you're performing operations on two or more tensors, they will need to be of the same *shape* - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the `np.*_like()` methods.
    1. `np.empty_like(x):`
    2. `np.zeros_like(x):`
    3. `np.empty_like(x):`

In [ ]:
zeros = np.zeros((2, 3))
print(zeros)

ones = np.ones((2, 3))
print(ones)

np.random.seed(1729)
random = np.random.rand(2, 3)
print(random)

x = np.empty((3, 4))
print(type(x))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.2121586  0.25901824 0.42352188]
 [0.71966101 0.69225093 0.72817482]]
<class 'numpy.ndarray'>
[[1.74976547 0.3426804  1.1530358  0.25243604]
 [0.98132079 0.51421884 0.22117967 1.07004333]
 [0.18949583 0.25500144 0.45802699 0.43516349]]


In [ ]:
# np.arrange():
zero_to_ten = np.arange(start=0, stop=10, step=1, dtype=float)
zero_to_ten.astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## np.*_like()
x = np.empty((2, 2, 3))
print(x.shape)
print(x)

empty_like_x = np.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = np.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = np.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

(2, 2, 3)
[[[1.74976547 0.3426804  1.1530358 ]
  [0.25243604 0.98132079 0.51421884]]

 [[0.22117967 1.07004333 0.18949583]
  [0.25500144 0.45802699 0.43516349]]]
(2, 2, 3)
[[[1.74976547 0.3426804  1.1530358 ]
  [0.25243604 0.98132079 0.51421884]]

 [[0.22117967 1.07004333 0.18949583]
  [0.25500144 0.45802699 0.43516349]]]
(2, 2, 3)
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## [5. Data Type:](#h_cell)
<a id='dtype_cell'></a>

In [ ]:
zero_to_ten = np.arange(start=0, stop=10, step=1, dtype=float) # declare a float data type
zero_to_ten.astype(int) # change the data type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## [6. Math and Logical Operations:](#h_cell)
<a id='math_cell'></a>

In [ ]:
ones = np.zeros((2, 2)) + 1 #addition ones.add()
ones=np.add(ones,100)
twos = np.ones((2, 2)) * 2 #multiplication
threes = (np.ones((2, 2)) * 7 - 1) / 2 # complex operation
fours = twos ** 2 # squre
sqrt2s = twos ** 0.5 ## squre root

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

[[101. 101.]
 [101. 101.]]
[[2. 2.]
 [2. 2.]]
[[3. 3.]
 [3. 3.]]
[[4. 4.]
 [4. 4.]]
[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]


1. `np.clip(a, a_min, a_max, out=None):` It is used to limit the values of an array or a scalar within a specified range.
- a = array that should be cliped.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a_clipped = np.clip(a, 2, 4)
a_clipped

array([2, 2, 3, 4, 4])

### 6.1 Matrix multiplication
numpy implements matrix multiplication functionality in the `np.dot(a,b) or np.matmul(a,b)` method.


1. The inner dimensions must match:

        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the outer dimensions: `(batch_size, A.shape[-2], B.shape[-1])`

        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)
3. When you use `@ or matmul` on arrays with more than 2 dimensions, NumPy only looks at the last two axes. It treats those as the actual matrix. Every single axis before that is treated as a "batch" dimension and is simply broadcast/looped over.

### 6.2 Element wise multiplication:
PyTorch implements multiplication functionality in the `np.multiply` or `*` method.

        (3, 2) @ (2, 3) won't work
        (2, 3) @ (3, 3) will work

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# ❌ NOT Matrix Multiplication!
A * B   
# [[1*5, 2*6],   → [[ 5, 12],
#  [3*7, 4*8]]      [21, 32]]  (Element-wise)

# ✅ ACTUAL Matrix Multiplication
A @ B   
# [[1*5 + 2*7, 1*6 + 2*8],   → [[19, 22],
#  [3*5 + 4*7, 3*6 + 4*8]]      [43, 50]]

array([[19, 22],
       [43, 50]])

In [ ]:
input = np.random.rand(10, 3, 4)
w= np.random.rand(4,4) # this will work
(input@w).shape

(10, 3, 4)

In [ ]:
bias = np.random.rand(3)  # Channel bias
bias.shape


(3,)

## Einstein Summation
Standard NumPy requires you to reshape, transpose, and do multiple steps. einsum does it in one shot, which is faster and uses less memory.


```
┌─────────────────────────────────────────────────────────────────┐
│                    EINSUM CHEAT SHEET                           │
├─────────────────────────────────────────────────────────────────┤
│  SYMBOLS                                                        │
│  ├── Letters (i,j,k)    → Dimensions                            │
│  ├── Repeated on LEFT   → Multiply & SUM (Contract)             │
│  ├── Appears on RIGHT   → KEEP in output                        │
│  └── Missing on RIGHT   → SUMMED AWAY (Reduced)                 │
├─────────────────────────────────────────────────────────────────┤
│  1D OPERATIONS                                                  │
│  ├── 'i->'              → Sum vector                            │
│  ├── 'i,i->'            → Dot product                           │
│  └── 'i,i->i'           → Element-wise multiply                 │
├─────────────────────────────────────────────────────────────────┤
│  2D OPERATIONS                                                  │
│  ├── 'ij->ji'           → Transpose                             │
│  ├── 'ij,jk->ik'        → Matrix Multiply (A @ B)               │
│  ├── 'ii->'             → Trace                                 │
│  ├── 'ii->i'            → Diagonal                              │
│  ├── 'ij->i'            → Row sum                               │
│  └── 'ij->j'            → Column sum                            │
├─────────────────────────────────────────────────────────────────┤
│  DEEP LEARNING SPECIFIC                                         │
│  ├── 'bmn,bnp->bmp'     → Batch MatMul                          │
│  ├── 'bhid,bhjd->bhij'  → Attention Scores (Q @ K.T)            │
│  ├── 'bd,cd->bc'        → Pairwise Distance / Similarity        │
│  └── 'bchw->bc'         → Global Average Pooling                │
└─────────────────────────────────────────────────────────────────┘
```

In [ ]:
import numpy as np
A = np.arange(12).reshape(3, 4)
B = np.arange(20).reshape(4, 5)

print(A@B)
print(np.einsum('ik, kj-> ij', A,B))


[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]]
[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]]


In [ ]:
# Element wise multiplication
A = np.arange(12).reshape(3, 4)
B = np.arange(12).reshape(3, 4)
print(A*B)
print(np.einsum('ij, ij-> ij', A,B))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [ ]:
#vector Product(vector)
A = np.arange(4).reshape(4)
B = np.arange(4).reshape(4)
print(A.dot(B))
print(np.einsum('i, i-> ', A,B))

14
14


### Outer product
the outer product of two vectors results in a matrix. If you have a vector $u$ of size $M$ and a vector $v$ of size $N$, their outer product will be an $M \times N$ matrix where every possible pair of elements is multiplied.
- Instead of reducing information into a single number (like dot product), the outer product preserves every combination.

In [ ]:
## Outer product
A = np.arange(4).reshape(4)
B = np.arange(4).reshape(4)
print(np.outer(A,B))
print(np.einsum('i, j-> ij', A,B))

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


In [ ]:
A = np.arange(12).reshape(3,4)
print(A,"\n", A.T)
print(np.einsum('ij-> ji', A))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# sum of diagonal
A = np.arange(16).reshape(-1,4)
print(A.trace())
print(np.einsum('ii-> ', A))

30
30


### 3D Tensors: Batched Linear Projections (RNNs/Embeddings) 
- (Batch, Sequence_Length, Features) = (B, S, D)

In [ ]:
B, S, D_in, D_out = 32, 10, 64, 128
X = np.random.rand(B, S, D_in)  # Input sequences
W = np.random.rand(D_in, D_out) # Weight matrix

np_out = X @ W  
# Shape: (32, 10, 128) ✅ Very clean!
out = np.einsum('bsd, do->bso', X, W, optimize=True)
# Shape: (32, 10, 128)
print(f" np_shape:{np_out.shape}\neinSum_shape:{out.shape}")

 np_shape:(32, 10, 128)
einSum_shape:(32, 10, 128)


### 4D Tensors: CNNs (Convolutional Neural Networks)
- Shape Convention: (Batch, Channels, Height, Width) = (B, C, H, W)

1. Global Average Pooling (GAP): `Flatten the spatial dimensions H, W by averaging them, keeping B, C.`

In [ ]:
# Global Average Pooling (GAP)
B, C, H, W = 8, 64, 28, 28
X = np.random.rand(B, C, H, W)
np_out = X.mean(axis=(2, 3)) # # Must explicitly specify which axes to collapse
out= np.einsum('bchw->bc', X)
print(f" np_shape:{np_out.shape}\neinSum_shape:{out.shape}")

 np_shape:(8, 64)
einSum_shape:(8, 64)


2. 1x1 Convolution (Channel Mixing): `A 1x1 conv is just a matrix multiplication across the channel dimension at every pixel location.`

In [ ]:
B, C_in, H, W = 8, 64, 28, 28
C_out = 128
X = np.random.rand(B, C_in, H, W)
w = np.random.rand(C_out, C_in)  # 1x1 conv weights # 128 x64

# You CANNOT just do X @ W because W is 2D and spatial dims are in the way.
# You have to reshape X, multiply, and reshape back.
X_reshaped = X.reshape(B, C_in, H*W)  # Shape: (8, 64, 784)
# Transpose to align for matmul
np_out = w @ X_reshaped          # Shape becomes: (8, 128, 784)
np_out = np_out.reshape(B, C_out, H,W)             # (8, 128, 28, 28) ✅

out= np.einsum('bchw, oi->bohw',X,w, optimize=True)

print(f" np_shape:{np_out.shape}\neinSum_shape:{out.shape}")


 np_shape:(8, 128, 28, 28)
einSum_shape:(8, 128, 28, 28)


### 5D Tensors: Video & Multi-Head Attention
- Shape Convention (Video): (Batch, Time, Channels, Height, Width) = (B, T, C, H, W)
- Shape Convention (Attention): (Batch, Heads, Seq, Dim) = (B, H, S, D)



1. Video Global Pooling: `Average out Time, Height, and Width. Keep Batch and Channels.`

In [130]:
B, T, C, H, W = 4, 30, 3, 128, 128
video = np.random.rand(B, T, C, H, W)

np_out = video.mean(axis=(1, 3, 4))
out= np.einsum('btchw->bc', video)
print(f" np_shape:{np_out.shape}\neinSum_shape:{out.shape}")

 np_shape:(4, 3)
einSum_shape:(4, 3)


2. Multi-Head Attention (The Holy Grail of einsum): `This is where einsum shines the most. In Transformers, you have Queries Q, Keys K, and Values V. Shapes: (Batch, Heads, Seq_Q, Dim) and (Batch, Heads, Seq_K, Dim).`


In [ ]:
B, H, S_q, S_k, D = 8, 12, 50, 100, 64

Q = np.random.rand(B, H, S_q, D) # (8, 12, 50, 64)
K = np.random.rand(B, H, S_k, D) # (8, 12, 100, 64)
V = np.random.rand(B, H, S_k, D) # (8, 12, 100, 64)

# Standard NumPy Way:
# Must explicitly transpose K's last two dims before multiplying
K_T = K.transpose(0, 1, 3, 2) # Shape: (8, 12, 64, 100)
np_scores = Q @ K_T               # Shape: (8, 12, 50, 100)

# einsum Way:
# Match 'd' (dim) to sum out. Keep 's' (seq_q) and 't' (seq_k).
scores = np.einsum('bhsd,bhtd->bhst', Q, K)
# Shape: (8, 12, 50, 100) ✅

print(f" np_shape:{np_scores.shape}\neinSum_shape:{scores.shape}")

 np_shape:(8, 12, 50, 100)
einSum_shape:(8, 12, 50, 100)


In [132]:
# Standard NumPy Way:
# scores is (8, 12, 50, 100), V is (8, 12, 100, 64)
np_context = scores @ V # Shape: (8, 12, 50, 64)

# einsum Way:
# Match 't' (seq_k) to sum out. Keep 's' (seq_q) and 'd' (dim).
context = np.einsum('bhst,bhtd->bhsd', scores, V)
# Shape: (8, 12, 50, 64) 

print(f" np_shape:{np_context.shape}\neinSum_shape:{context.shape}")

 np_shape:(8, 12, 50, 64)
einSum_shape:(8, 12, 50, 64)


3. Extracting 5D Diagonals (Contrastive Loss)
   - Imagine a 5D tensor representing pairwise similarities across batches, heads, and sequences. You only want the diagonal (where query index equals key index).

In [134]:
# Pairwise similarity matrix: (Batch, Heads, Seq_q, Seq_k, Seq_k)
# Let's say we just want the diagonal of the last two dimensions.
X = np.random.rand(8, 12, 50, 50, 50) 

# Standard NumPy Way:
# np.diag only works on 2D. You'd need a messy loop or advanced indexing.
np_diags = np.diagonal(X, axis1=-2, axis2=-1) 

# einsum Way:
# Repeat 'i' on the left side to indicate diagonal extraction!
diags = np.einsum('bhsii->bhsi', X)
# Shape: (8, 12, 50, 50) ✅ Absolutely elegant.

print(f" np_shape:{np_diags.shape}\neinSum_shape:{diags.shape}")

 np_shape:(8, 12, 50, 50)
einSum_shape:(8, 12, 50, 50)


### Summary

```
┌─────────────────────────────────────────────────────────────────────┐
│              NUMPY vs EINSUM DECISION MATRIX                        │
├─────────────────────────────────────────────────────────────────────┤
│                                                                     │
│  USE STANDARD NUMPY (@, *, .T):                                     │
│  ├── Simple Batched MatMul: (B, M, N) @ (B, N, P)                   │
│  ├── Adding Bias: (B, C, H, W) + (1, C, 1, 1)                       │
│  └── Simple Transpose: (B, C, H, W) -> (B, H, W, C)                 │
│                                                                     │
│  USE EINSUM:                                                        │
│  ├── Multiplying NON-adjacent dims (e.g., 1x1 Conv across spatial)  │
│  ├── Q @ K.T without explicitly transposing K (Attention)           │
│  ├── Summing out MIDDLE dimensions (e.g., GAP in CNNs)              │
│  ├── Extracting diagonals in batches (Contrastive learning)         │
│  └── Any operation where you'd otherwise need 3+ reshapes/transposes│
│                                                                     │
│  ALWAYS ADD `optimize=True` to einsum in production DL code!        │
└─────────────────────────────────────────────────────────────────────┘
```

### Common caution when to use `dot` or `matmul or @`
- For matrix multiplication, lower dimention `I-D or 2-D` both works fine.
- But when dimention greter than 2d `dot` does not work.

In [ ]:
# Shapes need to be in the right way  
tensor_A = np.array([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=np.float32)

tensor_B = np.array([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=np.float32)
print(f"tensor_A: {tensor_A.shape} \t {tensor_A.ndim}")
print(f"tensor_B: {tensor_B.shape} \t {tensor_B.ndim}")

print("Element wise:",np.multiply(tensor_A, tensor_B))
print("Transpose:",tensor_A.T.shape)

np.matmul(tensor_A.T, tensor_B) 

tensor_A: (3, 2) 	 2
tensor_B: (3, 2) 	 2
Element wise: [[ 7. 20.]
 [24. 44.]
 [45. 72.]]
Transpose: (2, 3)


array([[ 76., 103.],
       [100., 136.]], dtype=float32)

#### Element wise Multiplication:
$$[m\times n\times o] * [p\times q\times r]=[m\times n\times o]\text{ this will be the new shape}$$
* Each tensor must have at least one dimension - no empty tensors.
* Comparing the dimension sizes of the two tensors, **going from last to first:**
    * Each dimension must be equal $m=p\;, n=q,\; o=r $, **or**
    * One of the dimensions must be of size 1, $p=1\;, q=1,\; o=r=1 $**or**
    * The dimension does not exist in one of the tensors $q=1,\; o=r=1 $

In [ ]:
np.random.seed(100)
a= np.random.randint(1,3,(2,3,4))
b= np.random.randint(1,3,(1,4))
print(f"a*a={a*a},\n\na*b={(a*b)},\na.shape={a.shape},\t b.shape={b.shape}")

a*a=[[[1 1 4 4]
  [4 4 1 1]
  [1 1 1 4]]

 [[1 1 1 1]
  [4 1 1 4]
  [1 4 1 1]]],

a*b=[[[1 2 4 4]
  [2 4 2 2]
  [1 2 2 4]]

 [[1 2 2 2]
  [2 2 2 4]
  [1 4 2 2]]],
a.shape=(2, 3, 4),	 b.shape=(1, 4)


In [ ]:
a = np.ones((4, 3, 2))

b = a * np.random.randn(   2) # 3rd & 2nd dims identical to a, dim 1 absent
print("b:", b[:1])


c = a * np.random.randn( 3, 1) # 3rd dim = 1, 2nd dim identical to a
print("C:",c)

d = a * np.random.randn(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print("d", d)


b: [[[-0.45802699  0.43516349]
  [-0.45802699  0.43516349]
  [-0.45802699  0.43516349]]]
C: [[[-0.58359505 -0.58359505]
  [ 0.81684707  0.81684707]
  [ 0.67272081  0.67272081]]

 [[-0.58359505 -0.58359505]
  [ 0.81684707  0.81684707]
  [ 0.67272081  0.67272081]]

 [[-0.58359505 -0.58359505]
  [ 0.81684707  0.81684707]
  [ 0.67272081  0.67272081]]

 [[-0.58359505 -0.58359505]
  [ 0.81684707  0.81684707]
  [ 0.67272081  0.67272081]]]
d [[[-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]]

 [[-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]]

 [[-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]]

 [[-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]]]


## [7. Manipulating Tensor Shapes](#h_cell)
<a id='mts_cell'></a>

## [8. Array Accessing](#h_cell)
<a id='aa_cell'></a>

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[:, 1:4])


[[2 3 4]
 [7 8 9]]


In [ ]:

xy= np.loadtxt("../data/wine/wine.csv", delimiter=',', dtype=np.float32, skiprows=1)
n_samples=xy.shape[0]
# xy
xy[:, 1:]


array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], dtype=float32)

## [9. Important Methods:](#h_cell)
<a id='im_cell'></a>

1. `numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`:  is used to create an array of evenly spaced values over a specified range.

In [ ]:
arr = np.linspace(0, 1, num=10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Axis:
The direction along which an operation is performed.
```
For a 2D array (rows, columns):
- axis=0 → move DOWN through rows (vertical)
- axis=1 → move ACROSS columns (horizontal)
- axis=None → operate on ALL elements
```

In [ ]:
# !-D Array
import numpy as np
arr = np.array([10,20,30,40])
np.sum(arr, axis=0) # 100

100

In [ ]:
# 2-D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])  # shape (2, 3)

# axis=0: collapse rows (move DOWN)
np.sum(arr, axis=0)  # [5, 7, 9]
#       ↓   ↓   ↓
#       1+4 2+5 3+6

# axis=1: collapse columns (move ACROSS)
np.sum(arr, axis=1)  # [6, 15]
#       ↓       ↓
#       1+2+3   4+5+6

# axis=None: collapse everything
np.sum(arr, axis=None)  # 21

21

In [ ]:
arr = np.arange(24).reshape(2, 3, 4)
# shape: (2, 3, 4) = (depth, rows, cols)
# print(arr)
# axis=0: collapse depth
np.sum(arr, axis=0).shape  # (3, 4) - keeps rows & cols
# print(arr)
# axis=1: collapse rows  
# np.sum(arr, axis=1).shape  # (2, 4) - keeps depth & cols

# # axis=2: collapse columns
# np.sum(arr, axis=2).shape  # (2, 3) - keeps depth & rows

# # Multiple axes
# np.sum(arr, axis=(0, 1)).shape  # (4,) - keeps only cols
# np.sum(arr, axis=(1, 2)).shape  # (2,) - keeps only depth

(3, 4)

```
Layer 0:              Layer 1:              Result (sum along axis=0):
                    +
[0   1   2   3]     [12  13  14  15]     [12  14  16  18]
[4   5   6   7]  +  [16  17  18  19]  =  [20  22  24  26]
[8   9  10  11]     [20  21  22  23]     [28  30  32  34]
     ↑                    ↑                       ↑
  layer 0              layer 1            element-wise addition
```

In [ ]:
# 3D array: (2 layers, 3 rows, 4 columns)
arr_3d = np.arange(24).reshape(2, 3, 4)
print(arr_3d)
print(arr_3d.shape)  # (2, 3, 4)

# axis=0: Remove layers → shape (3, 4)
layer_sum = np.sum(arr_3d, axis=0)
print(layer_sum)

# axis=1: Remove rows → shape (2, 4)
row_sum = np.sum(arr_3d, axis=1)

# axis=2: Remove columns → shape (2, 3)
col_sum = np.sum(arr_3d, axis=2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [ ]:
arr_3d = np.arange(24).reshape(2, 3, 4)
print(arr_3d.shape)  # (2, 3, 4)

# axis=0: Remove layers → shape (3, 4)
layer_sum = np.sum(arr_3d, axis=0, keepdims=True)
print(layer_sum, layer_sum.shape)

(2, 3, 4)
[[[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]] (1, 3, 4)


## Reshape and Broadcasting
it changes the shape (dimensions) of an array without changing the underlying data.
| Operation | Input Shape | Output Shape | Use Case |
| :--- | :--- | :--- | :--- |
| `reshape(-1)` | `(3,4)` | `(12,)` | Flatten to 1D |
| `reshape(1,-1)` | `(3,4)` | `(1,12)` | Row vector |
| `reshape(-1,1)` | `(3,4)` | `(12,1)` | Column vector |
| `reshape(2,2,3)` | `(12,)` | `(2,2,3)` | Create 3D |
| `reshape(batch,-1)` | `(32,28,28)` | `(32,784)` | Flatten batch |
| `reshape(-1, 28, 28, 1)` | `(32,784)` | `(32,28,28,1)` | Add channel dim |

In [ ]:
# After convolution layers: (batch, channels, height, width)
conv_output = np.random.rand(32, 64, 7, 7)

# Flatten for fully connected layers
flattened = conv_output.reshape(32, -1)
print(f"Flattened shape: {flattened.shape}")  # (32, 3136) where 3136 = 64×7×7

# Reshape back for deconvolution (if needed)
reconstructed = flattened.reshape(32, 64, 7, 7)
print(f"Reconstructed shape: {reconstructed.shape}")  # (32, 64, 7, 7)

Flattened shape: (32, 3136)
Reconstructed shape: (32, 64, 7, 7)


## Broadcasting
Broadcasting is NumPy's ability to perform arithmetic on arrays of different shapes. It "stretches" the smaller array conceptually (without actually copying memory) to match the larger array.`Broadcasting works with ELEMENT-WISE operations, NOT matrix multiplication.`
- `Element-wise ops (+, -, *, /, **, etc.) → Use broadcasting`

```
1. Align from right
2. Missing dim = 1
3. Must match OR be 1
4. Output = max(dim)
```

```
Shape A: (4, 3)
Shape B: (    3)  ← Compare here first!
```

```
┌────────────────────────────────────────────────────────────────┐
│                 BROADCASTING CHEAT SHEET                       │
├────────────────────────────────────────────────────────────────┤
│  ALIGNMENT: Compare shapes from RIGHT to LEFT.                │
│                                                                │
│  WORKS:                                                        │
│  (5, 3) + (3,)    → (5, 3) + (1, 3) → (5, 3) ✅              │
│  (5, 3) + (1, 3)  → (5, 3) ✅                                 │
│  (5, 3) + (5, 1)  → (5, 3) ✅                                 │
│  (5, 3) + (1,)    → (5, 3) + (1, 1) → (5, 3) ✅              │
│                                                                │
│  FAILS:                                                        │
│  (5, 3) + (5,)    → (5, 3) vs (1, 5) → 3 != 5 ❌             │
│  (5, 3) + (3, 5)  → 5 != 3 AND 3 != 5 ❌                     │
│                                                                │
├────────────────────────────────────────────────────────────────┤
│  FIXES FOR (N, M) ops with (N,) vectors:                     │
│  vector.reshape(-1, 1) → makes it (N, 1) [COLUMN VECTOR] ✅   │
│  vector.reshape(1, -1) → makes it (1, N) [ROW VECTOR] ✅      │
│  np.mean(x, axis=k, keepdims=True) → keeps dim as 1 ✅        │
└────────────────────────────────────────────────────────────────┘
```

In [ ]:
#Scaler or 1-D
# Multiply all elements by 2
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
result = arr * 2  # 2 broadcasts to (2,3)
print(result)
# [[ 2,  4,  6],
#  [ 8, 10, 12]]

[[ 2  4  6]
 [ 8 10 12]]


```
<!-- Stretch dimension 1 (columns) -->
Array (2, 3)           Scalar
┌───────────┐          
│ 1   2   3 │    *  2
│ 4   5   6 │          
└───────────┘

<!-- The vector row is copied downward to fill the vertical space: -->
Array (2, 3)           Broadcasted Scalar (2, 3)
┌───────────┐          ┌───────────┐
│ 1   2   3 │    *     │ 2   2   2 │
│ 4   5   6 │          │ 2   2   2 │
└───────────┘          └───────────┘

<!-- Element-wise Math Operation -->

┌──────────────┬──────────────┬──────────────┐
│ (1 * 2) = 2  │ (2 * 2) = 4  │ (3 * 2) = 6  │
├──────────────┼──────────────┼──────────────┤
│ (4 * 2) = 8  │ (5 * 2) = 10 │ (6 * 2) = 12 │
└──────────────┴──────────────┴──────────────┘
```

In [ ]:
#Pattern 2: Vector + Matrix (Row-wise)
# Add same vector to each row
matrix = np.array([[1, 2, 3], # Shape: (2, 3)
                   [4, 5, 6]])
vector = np.array([10, 20, 30]) # Shape: (3,) and broadcast to (1,3)

result = matrix + vector  # (2,3) + (1,3)
print(result)
# [[11, 22, 33],
#  [14, 25, 36]]

[[11 22 33]
 [14 25 36]]


```
<!-- Stretch dimension 1 (columns) -->
Matrix (2, 3)          Vector (1, 3)
┌───────────┐          ┌────────────┐
│ 1   2   3 │    +     │ 10  20  30 │
│ 4   5   6 │          └────────────┘
└───────────┘

<!-- The vector row is copied downward to fill the vertical space: -->

Matrix (2, 3)          Broadcasted Vector (2, 3)
┌───────────┐          ┌────────────┐
│ 1   2   3 │    +     │ 10  20  30 │  <-- Row copied
│ 4   5   6 │          │ 10  20  30 │  <-- Row copied
└───────────┘          └────────────┘

<!-- Element-wise Math Operation -->
┌───────────────────┬───────────────────┬───────────────────┐
│ (1 + 10) = 11     │ (2 + 20) = 22     │ (3 + 30) = 33     │
├───────────────────┼───────────────────┼───────────────────┤
│ (4 + 10) = 14     │ (5 + 20) = 25     │ (6 + 30) = 36     │
└───────────────────┴───────────────────┴───────────────────┘
```

In [ ]:
# Add same column vector to each column
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]]) # shape(2,2)
col_vector = np.array([[10],
                       [20]]) # shape(2,1)

result = matrix + col_vector  # (2,3) + (2,1)
print(result)
# [[11, 12, 13],
#  [24, 25, 26]]

[[11 12 13]
 [24 25 26]]


```
<!-- Stretch the column -->

Matrix (2, 3)          Broadcasted Vector (2, 3)
┌───────────┐          ┌────────────┐
│ 1   2   3 │    +     │ 10  10  10 │
│ 4   5   6 │          │ 20  20  20 │
└───────────┘          └────────────┘

<!-- Element-wise Math Operation -->
┌───────────────────┬───────────────────┬───────────────────┐
│ (1 + 10) = 11     │ (2 + 10) = 12     │ (3 + 10) = 13     │
├───────────────────┼───────────────────┼───────────────────┤
│ (4 + 20) = 24     │ (5 + 20) = 25     │ (6 + 20) = 26     │
└───────────────────┴───────────────────┴───────────────────┘
```

In [ ]:
def batch_norm(x, gamma, beta, eps=1e-5):
    """
    x: (batch, features)
    gamma, beta: (features,)
    """
    # Compute statistics along batch dimension
    mean = np.mean(x, axis=0, keepdims=True)  # (1, features) without kimdim the shape(128)
    var = np.var(x, axis=0, keepdims=True)    # (1, features)
    
    # Normalize
    x_norm = (x - mean) / np.sqrt(var + eps)  # Broadcasting! ((32,128)-(1,128))/np.sqrt((1,128)-scaler)
    
    # Scale and shift (broadcasting again)
    return x_norm * gamma + beta  # gamma, beta broadcast to (batch, features)

# Example
batch = np.random.randn(32, 128)  # 32 samples, 128 features
gamma = np.random.randn(128)
beta = np.random.randn(128)

normalized = batch_norm(batch, gamma, beta)
print(normalized.shape)  # (32, 128)

(32, 128)


In [ ]:
# Neural network layer: Z = X @ W + b
batch_size, input_dim, output_dim = 32, 784, 256

# Input batch
X = np.random.randn(batch_size, input_dim)  # (32, 784)

# Weights and bias
W = np.random.randn(input_dim, output_dim)  # (784, 256)
b = np.random.randn(output_dim)              # (256,)

# Forward pass
Z = X @ W + b  # (32,256) + (256,) broadcasts to (32,256)
print(Z.shape)  # (32, 256)
# b is added to each row (each sample) automatically!

(32, 256)


In [ ]:
# Attention
# Create causal mask for transformer
seq_len = 5

# Scores shape: (batch, heads, seq_len, seq_len)
scores = np.random.randn(2, 8, seq_len, seq_len)

# Create mask: (seq_len, seq_len)
mask = np.tril(np.ones((seq_len, seq_len)))  # Lower triangular

# Apply mask (broadcasting to batch and heads dimensions)
masked_scores = scores * mask  # (2,8,5,5) * (5,5) -> broadcasts!
print(masked_scores.shape)  # (2, 8, 5, 5)

# Fill masked positions with -inf
masked_scores = np.where(mask == 0, -np.inf, scores)

(2, 8, 5, 5)


### 4D Tensors: CNNs (Convolutional Neural Networks) (Batch, Channels, Height, Width) = (B, C, H, W)


#### A 1x1 conv is just a matrix multiplication across the channel dimension at every pixel location.



#### Scenario C: Squeeze-and-Excitation (SE Block) Attention


###  5D Tensors: Video & Multi-Head Attention
- Shape Convention (Video): (Batch, Time, Channels, Height, Width) = (B, T, C, H, W)
- Shape Convention (Attention): (Batch, Heads, Seq, Dim) = (B, H, S, D)